# Generated by Django 3.0 on 2019-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_uploadedfile_uploaddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationFile', models.FileField(upload_to='')),
                ('smokingReportFile', models.FileField(upload_to='')),
            ],
        ),
    ]
