# Generated by Django 3.0 on 2019-12-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_clusterfileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterfileupload',
            name='ownerID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
