# Generated by Django 3.0 on 2019-12-04 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_clusterfileupload_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterfileupload',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
